# Generated by Django 2.2 on 2019-04-27 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20190427_0346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='project_requirement',
            new_name='message',
        ),
    ]
